name: Docker

on:
  push:
    branches:
      - demo

env:
  IMAGE_NAME: azure-voting-app-redis
  RESOURCE_NAME: meetup20201119
  RESOURCE_GROUP: meetup-rg

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: |
            cd azure-vote
            az acr build --image demo/${{ env.IMAGE_NAME }}:latest \
            --registry ${{ env.RESOURCE_NAME }} \
            --file Dockerfile .

  deploy_to_aci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to ACI
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: |
            cd templates
            az container delete -g ${{ env.RESOURCE_GROUP }} -n ${{ env.RESOURCE_NAME }} -y
            az container create -g ${{ env.RESOURCE_GROUP }} -l eastus --file aci.yaml

  deploy_to_aks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to ACI
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: |
            cd templates
            az aks create --resource-group meetup_rg --name ${{ env.RESOURCE_NAME }} --node-count 1 --generate-ssh-keys
            az aks install-cli
            az aks get-credentials -g ${{ env.RESOURCE_GROUP }} -n ${{ env.RESOURCE_NAME }}
            kubectl apply -f aks.yaml
